### ISSUE TITLE
Mutiple - Display issue with Firefox 51 (and next versions) 64 bits

### ISSUE THREAD

**Issue by Iznogood1** [dingyi1993/jquery-magicsearch#1]
Hi, nice plugin,

unfortunately look what happens when using multiple labels under FF 51 64 bits :(
(display is ok with IE and Chrome)
![image](https://cloud.githubusercontent.com/assets/13468970/25422968/20226cda-2a63-11e7-90e7-9c5bed23a516.png)

**Comment by dingyi1993** [comment]
Thanks for your issue ,but I'm a little busy in recent days,maybe I'll solve this problem in this weekend,and then I'll send a email to you :)

**Comment by dingyi1993** [comment]
I have fixed this prooblem,caused by input's default display is inline in FF 51.
