### ISSUE TITLE
Pre populate with values

### ISSUE THREAD

**Issue by ashishbakde** [dingyi1993/jquery-magicsearch#2]
It is really a nice plugin but I am not able to find a solution to prepopulate magic search with some values.Is it possible to prepopulate the magic search with values? if so then how ?

**Comment by dingyi1993** [comment]
If your script like this
```
var dataSource = [
    {id: 1, firstName: 'Tim', lastName: 'Cook'},
    {id: 2, firstName: 'Eric', lastName: 'Baker'},
    {id: 3, firstName: 'Victor', lastName: 'Brown'},
];
$('#start-magicsearch').magicsearch({
    dataSource: dataSource,
    id: 'id',
    ......
});
```
you can add data-id on your input,like this
```
<input data-id="1,3">
```
now you will see some values were populated in your input.

**Comment by ashishbakde** [comment]
It's working for me now

Thanks
