### ISSUE TITLE
full width input

### ISSUE THREAD

**Issue by hakkim** [dingyi1993/jquery-magicsearch#4]
In this plugin I could see a width of '350px' coming from javascript for '.magicsearch-wrapper' element. How to do it with full width input types?

**Comment by dingyi1993** [comment]
Good catch! I'm on it!

**Comment by pranshu1995** [comment]
Hey @dingyi1993 
Any update on this?

**Comment by dingyi1993** [comment]
> Hey @dingyi1993
> Any update on this?

You reminded me, I will fix it in this weekend.

**Comment by dingyi1993** [comment]
@hakkim @pranshu1995 
After I check my code, I found '350px' is set up by my demo style.
https://github.com/dingyi1993/jquery-magicsearch/blob/64442d580ab914bee37a980d749d0e5242704fa5/examples/css/style.css#L49
You can set your own width by yourself.
Resolved your problem?

**Comment by hakkim** [comment]
Yes. This will solve the issues.
