### ISSUE TITLE
When No record is found i get chinese text

### ISSUE THREAD

**Issue by moh-imran** [dingyi1993/jquery-magicsearch#5]
Hello Dear,
When i filter records and dont find any result. I get this chinese text. 
未 搜索 到 结果
I want to remove it. 
Thanks in advance.

**Comment by davemerrill** [comment]
Hi, when you configure magic search, pass noResult: 'No tags found.', or whatever text you want to appear.

**Comment by dingyi1993** [comment]
@themifycloud 
@davemerrill is right, just config 'noResult'.
