### ISSUE TITLE
No option to set selected item programmatically

### ISSUE THREAD

**Issue by laurence73** [dingyi1993/jquery-magicsearch#6]
Is there any way to programmatically set the selected item?

**Comment by pankajBsharp** [comment]
I am also looking for this feature please let me know if you fixed this or you fixed this with some other plugin.

**Comment by laurence73** [comment]
I am using select2 now.

**Comment by dingyi1993** [comment]
> I am also looking for this feature please let me know if you fixed this or you fixed this with some other plugin.

Sorry for so long to reply, I've add this feature in v1.0.4, you can use like:

```$('#basic').trigger('set', { id: '3' });```

or multi:

```$('#multi').trigger('set', { id: '3,4' });```

with override:

```$('#multi').trigger('set', { id: '3,4', override: true });```
